### ISSUE TITLE
Error using reGeorg as socks5 sock for curl

### ISSUE THREAD

**Issue by epinna** [sensepost/reGeorg#9]
Whether I use reGeorg as socks5 tunnel by curl with the string

```
$ curl --socks5 localhost:8888 http://www.google.com
curl: (7) Failed to receive SOCKS5 connect request ack.
$
```

And reGeorg sock daemon prints out an error

```
$ python reGeorgSocksProxy.py -u http://localhost/environment/tunnel.php
...
[INFO   ]  Log Level set to [INFO]
[INFO   ]  Starting socks server [127.0.0.1:8888], tunnel at [http://localhost/environment/tunnel.php]
[INFO   ]  Checking if Georg is ready
[INFO   ]  Georg says, 'All seems fine'
[ERROR  ]  timed out
[ERROR  ]  'NoneType' object has no attribute '__getitem__'
```

Please note that reGeorge works properly if I use `--proxy4` as curl option.

**Comment by badbob** [comment]
Have a very similar issue:

```
$ curl -x socks5://localhost:8888 http://google.com
```

In reGeorg console I see:

```
[ERROR]  'NoneType' object has no attribute '__getitem__'
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\home\badbob\projects\reGeorg\reGeorgSocksProxy.py", line 351, in run
    self.closeRemoteSession()
  File "C:\home\badbob\projects\reGeorg\reGeorgSocksProxy.py", line 248, in closeRemoteSession
    log.info("[%s:%d] Connection Terminated" % (self.target, self.port))
AttributeError: 'session' object has no attribute 'target'
```
If I try to use socks4 protocol, I get just:

```
$curl -x socks4://localhost:8888 -k http://google.com
curl: (7) Can't complete SOCKS4 connection to 32.???.??.??:76. (145), Unknown.
```

**Comment by sanderfoobar** [comment]
Same issue for me with `--socks5`

**Comment by phra** [comment]
can this be caused by the fact that `regOrg` is not supporting multiple connections at the same time?

`CONNECT` requests always override `$_SESSION[]` buffers because they are not parametrized by client's IP:PORT pair.

**Comment by Maskhe** [comment]
'session' object has no attribute 'target'
